global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${FROM_EMAIL}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'default'
  email_configs:
  - to: 'admin@immigration-suite.gov'
    subject: '[Immigration Suite] Alert: {{ .GroupLabels.alertname }}'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Service: {{ .GroupLabels.service }}
      
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@immigration-suite.gov,ops@immigration-suite.gov'
    subject: '[CRITICAL] Immigration Suite Alert: {{ .GroupLabels.alertname }}'
    body: |
      🚨 CRITICAL ALERT 🚨
      
      Alert: {{ .GroupLabels.alertname }}
      Service: {{ .GroupLabels.service }}
      
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Started: {{ .StartsAt }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'admin@immigration-suite.gov'
    subject: '[WARNING] Immigration Suite Alert: {{ .GroupLabels.alertname }}'
    body: |
      ⚠️ Warning Alert
      
      Alert: {{ .GroupLabels.alertname }}
      Service: {{ .GroupLabels.service }}
      
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Started: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'service']